### ISSUE TITLE
Do not allow clicking (Stopping/starting) the video, it makes it so everyone is out of sync

### ISSUE THREAD

**Issue by drorwolmer** [drorwolmer/haminetNG#13]

**Comment by drorwolmer** [comment]
clicking the link also "opens a new tab" and then haminet in unusable

**Comment by Matityahul** [comment]
> clicking the link also "opens a new tab" and then haminet in unusable

I would allow to click the link, but open it in Chrome (if it possible)

**Comment by drorwolmer** [comment]
thanks @smuk3c for the PR this closes our first issue!
