### ISSUE TITLE
CSS Styles are different between dev and prod

### ISSUE THREAD

**Issue by drorwolmer** [drorwolmer/haminetNG#21]
I have no idea why, maybe @smuk3c will know

**Comment by smuk3c** [comment]
@drorwolmer do we have screenshots or more details where difference is?

**Comment by drorwolmer** [comment]
checkout the buttons outline

PROD:
![image](https://user-images.githubusercontent.com/6145197/97899910-9a609500-1d42-11eb-9c4d-7707edf600ef.png)

DEV:
![image](https://user-images.githubusercontent.com/6145197/97899941-a8aeb100-1d42-11eb-8291-aa4785430163.png)

**Comment by drorwolmer** [comment]
its something to do with `app.global.css`
